version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    volumes:
      - ./user-service:/usr/src/app
    depends_on:
      - mongo
  chat-service:
    build:
      context: ./chat-service
    ports:
      - "4000:4000"
    volumes:
      - ./chat-service:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
