swagger: "2.0"
info:
  version: "1.0.0"
  title: "Chat Service API"
  description: "API documentation for the chat service"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /sendMessage:
    post:
      summary: "Send a message"
      description: "Send a message to another user"
      parameters:
        - in: body
          name: message
          description: "Message content"
          required: true
          schema:
            type: object
            properties:
              receiverId:
                type: string
                description: "ID of the recipient user"
              messageContent:
                type: string
                description: "Content of the message"
      responses:
        200:
          description: "Message sent successfully"
        401:
          description: "User session verification failed"
        500:
          description: "Internal server error"
  /getChatHistory:
    get:
      summary: "Get chat history"
      description: "Retrieve chat history for the authenticated user"
      responses:
        200:
          description: "Chat history retrieved successfully"
          schema:
            type: array
            items:
              $ref: "#/definitions/ChatMessage"
        401:
          description: "User session verification failed"
        500:
          description: "Internal server error"
definitions:
  ChatMessage:
    type: object
    properties:
      messageId:
        type: string
        description: "ID of the message"
      sender:
        type: string
        description: "ID of the sender"
      receiver:
        type: string
        description: "ID of the receiver"
      message:
        type: string
        description: "Content of the message"
      timestamp:
        type: object
        properties:
          date:
            type: string
            format: date
            description: "Date of the message"
          time:
            type: string
            format: time
            description: "Time of the message"